import dns from 'node:dns';
dns.setServers(['8.8.8.8', '8.8.4.4']);

import { Outfit } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import { ToastContainer } from "react-toastify";
import Footer from "@/components/shared/Footer";



const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      data-theme="light"
      lang="en"
      className={`${outfit.className} h-full antialiased`}
    >
      <body suppressHydrationWarning className="min-h-full flex flex-col">
        <Navbar></Navbar>
        <main className="w-10/12 mx-auto flex-1">
          {children}
        </main>
        <Footer></Footer>
        <ToastContainer/>
      </body>
    </html>
  );
}
